services:
  spring:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/code
      - logvolume01:/var/log
    networks:
      - db
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: henlo
volumes:
  logvolume01: {}

networks:
  db:
    name: bridge_db
    driver: bridge