services:
  spring:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: henlo
    ports:
      - "5001:5432"
volumes:
  logvolume01: {}